### ISSUE TITLE
Error when tap on "." char

### ISSUE THREAD

**Issue by sci92bior** [flytreeleft/flutter_calculator#1]
After a successful implementation of your calculator to my app unfortunately I received an error. When I tap on dot after I chose a number, Flutter throw me something like this: 

> 'SubListIterable<MathSymbol>' is not a subtype of type 'List<MathSymbol>'
> 
> When the exception was thrown, this was the stack: 
> #0      MathFormula.getSymbols (package:flutter_calculator/src/math_formula.dart:122:5)
> #1      MathFormulaValidator.isAccepted (package:flutter_calculator/src/math_formula_validator.dart:73:12)
> #2      MathFormula._addSymbolAtCursor (package:flutter_calculator/src/math_formula.dart:168:26)
> #3      MathFormula.process (package:flutter_calculator/src/math_formula.dart:81:14)
> #4      _MathFormulaViewState._processMathSymbolAtCursor (package:flutter_calculator/src/math_formula_view.dart:115:19)

**Comment by flytreeleft** [comment]
@sci92bior Thank you. I just confirmed that it is a bug. I will fix it as soon as possible :).

**Comment by flytreeleft** [comment]
@sci92bior The bug is already fixed, please try to use the latest code. Thanks!

**Comment by sci92bior** [comment]
@flytreeleft thank's a lot! Excellent work!
